title: quTea
author: Claudio Lira
email: klaldju@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  We talk about quantum programming and machine learning. Short chunks of science for people in a hurry.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
